insert into public.provinces (id, slug, name_en, name_ur) values
  (1, 'punjab', 'Punjab', 'پنجاب'),
  (2, 'sindh', 'Sindh', 'سندھ'),
  (3, 'kpk', 'Khyber Pakhtunkhwa', 'خیبر پختونخوا'),
  (4, 'balochistan', 'Balochistan', 'بلوچستان'),
  (5, 'islamabad', 'Islamabad Capital', 'اسلام آباد'),
  (6, 'ajk', 'Azad Kashmir', 'آزاد کشمیر'),
  (7, 'gb', 'Gilgit-Baltistan', 'گلگت بلتستان')
on conflict (id) do nothing;

insert into public.cities (slug, name_en, name_ur, province_id, is_major) values
  ('karachi','Karachi','کراچی',2,true),
  ('lahore','Lahore','لاہور',1,true),
  ('islamabad','Islamabad','اسلام آباد',5,true),
  ('rawalpindi','Rawalpindi','راولپنڈی',1,true),
  ('faisalabad','Faisalabad','فیصل آباد',1,true),
  ('multan','Multan','ملتان',1,true),
  ('peshawar','Peshawar','پشاور',3,true),
  ('quetta','Quetta','کوئٹہ',4,true),
  ('gujranwala','Gujranwala','گوجرانوالہ',1,true),
  ('sialkot','Sialkot','سیالکوٹ',1,true),
  ('hyderabad','Hyderabad','حیدرآباد',2,true),
  ('bahawalpur','Bahawalpur','بہاولپور',1,false),
  ('sargodha','Sargodha','سرگودھا',1,false),
  ('sukkur','Sukkur','سکھر',2,false),
  ('larkana','Larkana','لاڑکانہ',2,false),
  ('sheikhupura','Sheikhupura','شیخوپورہ',1,false),
  ('mardan','Mardan','مردان',3,false),
  ('mingora','Mingora','مینگورہ',3,false),
  ('rahim-yar-khan','Rahim Yar Khan','رحیم یار خان',1,false),
  ('jhang','Jhang','جھنگ',1,false),
  ('dera-ghazi-khan','Dera Ghazi Khan','ڈیرہ غازی خان',1,false),
  ('gujrat','Gujrat','گجرات',1,false),
  ('sahiwal','Sahiwal','ساہیوال',1,false),
  ('wah','Wah Cantt','واہ کینٹ',1,false),
  ('kasur','Kasur','قصور',1,false),
  ('okara','Okara','اوکاڑہ',1,false),
  ('chiniot','Chiniot','چنیوٹ',1,false),
  ('kamoke','Kamoke','کاموکی',1,false),
  ('hafizabad','Hafizabad','حافظ آباد',1,false),
  ('sadiqabad','Sadiqabad','صادق آباد',1,false),
  ('kohat','Kohat','کوہاٹ',3,false),
  ('khanewal','Khanewal','خانیوال',1,false),
  ('dera-ismail-khan','Dera Ismail Khan','ڈیرہ اسماعیل خان',3,false),
  ('turbat','Turbat','تربت',4,false),
  ('abbottabad','Abbottabad','ایبٹ آباد',3,false),
  ('mirpur-khas','Mirpur Khas','میرپور خاص',2,false),
  ('mansehra','Mansehra','مانسہرہ',3,false),
  ('nawabshah','Nawabshah','نواب شاہ',2,false),
  ('khuzdar','Khuzdar','خضدار',4,false),
  ('muzaffargarh','Muzaffargarh','مظفر گڑھ',1,false),
  ('vehari','Vehari','وہاڑی',1,false),
  ('pakpattan','Pakpattan','پاکپتن',1,false),
  ('bhakkar','Bhakkar','بھکر',1,false),
  ('khairpur','Khairpur','خیرپور',2,false),
  ('jacobabad','Jacobabad','جیکب آباد',2,false),
  ('chishtian','Chishtian','چشتیاں',1,false),
  ('muridke','Muridke','مرید کے',1,false),
  ('mirpur-ajk','Mirpur (AJK)','میرپور',6,false),
  ('gilgit','Gilgit','گلگت',7,false),
  ('skardu','Skardu','سکردو',7,false)
on conflict (slug) do nothing;

insert into public.categories (slug, name_en, name_ur, icon, sort_order) values
  ('mistri','Mistri (Construction)','مستری','HardHat',10),
  ('mazdoor','Mazdoor (General Labour)','مزدور','Hammer',15),
  ('plumber','Plumber','پلمبر','Wrench',20),
  ('electrician','Electrician','الیکٹریشن','Plug',25),
  ('carpenter','Carpenter (Tarkhan)','ترکھان','Hammer',30),
  ('painter','Painter','رنگ ساز','PaintRoller',35),
  ('mason','Mason (Raj Mistri)','راج مستری','Brick',40),
  ('ac-technician','AC Technician','اے سی مکینک','Snowflake',45),
  ('appliance-repair','Appliance Repair','آلات کی مرمت','Refrigerator',50),
  ('welder','Welder','ویلڈر','Flame',55),
  ('tile-installer','Tile Installer','ٹائل لگانے والا','Grid3x3',60),
  ('glass-cutter','Glass Cutter','شیشے والا','Square',65),
  ('house-cleaner','House Cleaner','گھر کی صفائی','Sparkles',70),
  ('sofa-cleaner','Sofa & Carpet Cleaner','صوفہ و قالین صفائی','Sofa',75),
  ('safai-wali','Safai Wali (Maid)','صفائی والی','Brush',80),
  ('car-washer','Car Washer','گاڑی دھونے والا','Car',85),
  ('gardener','Gardener (Mali)','مالی','Trees',90),
  ('cook','Cook (Bawarchi)','باورچی','ChefHat',95),
  ('driver','Driver','ڈرائیور','Car',100),
  ('tailor','Tailor (Darzi)','درزی','Scissors',105),
  ('tutor','Home Tutor','ٹیوٹر','BookOpen',110),
  ('mehndi-artist','Mehndi Artist','مہندی والی','Flower',115),
  ('beautician','Beautician (Home Service)','بیوٹیشن','Heart',120),
  ('auto-mechanic','Auto Mechanic','گاڑی مکینک','Wrench',125),
  ('bike-mechanic','Bike Mechanic','بائیک مکینک','Bike',130),
  ('mobile-repair','Mobile Repair','موبائل مرمت','Smartphone',135),
  ('computer-repair','Computer Repair','کمپیوٹر مرمت','Laptop',140),
  ('cctv-solar','CCTV / Solar Installer','سی سی ٹی وی / سولر','Camera',145),
  ('pest-control','Pest Control','کیڑے مار','Bug',150),
  ('movers-packers','Movers & Packers','سامان شفٹنگ','Truck',155)
on conflict (slug) do nothing;

do $$
declare lhr int; khi int; isl int; rwp int;
begin
  select id into lhr from public.cities where slug='lahore';
  select id into khi from public.cities where slug='karachi';
  select id into isl from public.cities where slug='islamabad';
  select id into rwp from public.cities where slug='rawalpindi';

  insert into public.areas (city_id, slug, name_en, name_ur) values
    (lhr,'johar-town','Johar Town','جوہر ٹاؤن'),
    (lhr,'dha','DHA','ڈی ایچ اے'),
    (lhr,'gulberg','Gulberg','گلبرگ'),
    (lhr,'model-town','Model Town','ماڈل ٹاؤن'),
    (lhr,'wapda-town','Wapda Town','واپڈا ٹاؤن'),
    (lhr,'bahria-town','Bahria Town','بحریہ ٹاؤن'),
    (lhr,'cantt','Cantt','چھاؤنی'),
    (lhr,'iqbal-town','Iqbal Town','اقبال ٹاؤن'),
    (lhr,'township','Township','ٹاؤن شپ'),
    (lhr,'garden-town','Garden Town','گارڈن ٹاؤن'),
    (lhr,'faisal-town','Faisal Town','فیصل ٹاؤن'),
    (lhr,'samanabad','Samanabad','ثمن آباد'),
    (lhr,'shadman','Shadman','شادمان'),
    (lhr,'gulshan-ravi','Gulshan-e-Ravi','گلشن راوی'),
    (lhr,'walton','Walton','والٹن'),
    (lhr,'raiwind','Raiwind Road','ریوینڈ روڈ'),
    (lhr,'ferozepur-road','Ferozepur Road','فیروزپور روڈ'),
    (lhr,'multan-road','Multan Road','ملتان روڈ'),
    (lhr,'thokar','Thokar Niaz Baig','ٹھوکر نیاز بیگ'),
    (lhr,'allama-iqbal-town','Allama Iqbal Town','علامہ اقبال ٹاؤن'),

    (khi,'gulshan','Gulshan-e-Iqbal','گلشن اقبال'),
    (khi,'dha-karachi','DHA','ڈی ایچ اے'),
    (khi,'clifton','Clifton','کلفٹن'),
    (khi,'north-nazimabad','North Nazimabad','نارتھ ناظم آباد'),
    (khi,'nazimabad','Nazimabad','ناظم آباد'),
    (khi,'malir','Malir','ملیر'),
    (khi,'korangi','Korangi','کورنگی'),
    (khi,'landhi','Landhi','لانڈھی'),
    (khi,'orangi','Orangi Town','اورنگی ٹاؤن'),
    (khi,'fb-area','F.B. Area','ایف بی ایریا'),
    (khi,'pechs','PECHS','پی ای سی ایچ ایس'),
    (khi,'tariq-road','Tariq Road','طارق روڈ'),
    (khi,'saddar','Saddar','صدر'),
    (khi,'gulistan-johar','Gulistan-e-Johar','گلستان جوہر'),
    (khi,'shah-faisal','Shah Faisal Colony','شاہ فیصل کالونی'),
    (khi,'north-karachi','North Karachi','نارتھ کراچی'),
    (khi,'new-karachi','New Karachi','نیو کراچی'),
    (khi,'lyari','Lyari','لیاری'),
    (khi,'bahadurabad','Bahadurabad','بہادر آباد'),
    (khi,'scheme-33','Scheme 33','سکیم 33'),

    (isl,'f-6','F-6','ایف-6'),
    (isl,'f-7','F-7','ایف-7'),
    (isl,'f-8','F-8','ایف-8'),
    (isl,'f-10','F-10','ایف-10'),
    (isl,'f-11','F-11','ایف-11'),
    (isl,'g-6','G-6','جی-6'),
    (isl,'g-7','G-7','جی-7'),
    (isl,'g-8','G-8','جی-8'),
    (isl,'g-9','G-9','جی-9'),
    (isl,'g-10','G-10','جی-10'),
    (isl,'g-11','G-11','جی-11'),
    (isl,'g-13','G-13','جی-13'),
    (isl,'i-8','I-8','آئی-8'),
    (isl,'i-9','I-9','آئی-9'),
    (isl,'i-10','I-10','آئی-10'),
    (isl,'e-11','E-11','ای-11'),
    (isl,'bahria-isl','Bahria Town','بحریہ ٹاؤن'),
    (isl,'dha-isl','DHA','ڈی ایچ اے'),
    (isl,'pwd','PWD','پی ڈبلیو ڈی'),
    (isl,'gulberg-isl','Gulberg Greens','گلبرگ گرینز'),

    (rwp,'saddar-rwp','Saddar','صدر'),
    (rwp,'satellite-town','Satellite Town','سیٹلائٹ ٹاؤن'),
    (rwp,'committee-chowk','Committee Chowk','کمیٹی چوک'),
    (rwp,'raja-bazaar','Raja Bazaar','راجہ بازار'),
    (rwp,'chaklala','Chaklala Scheme 3','چکلالہ سکیم 3'),
    (rwp,'westridge','Westridge','ویسٹ رج'),
    (rwp,'pwd-rwp','PWD','پی ڈبلیو ڈی'),
    (rwp,'bahria-rwp','Bahria Town','بحریہ ٹاؤن'),
    (rwp,'dha-rwp','DHA','ڈی ایچ اے'),
    (rwp,'gulraiz','Gulraiz','گلریز'),
    (rwp,'morgah','Morgah','مورگاہ'),
    (rwp,'adyala-road','Adyala Road','اڈیالہ روڈ'),
    (rwp,'peshawar-road','Peshawar Road','پشاور روڈ'),
    (rwp,'murree-road','Murree Road','مری روڈ')
  on conflict (city_id, slug) do nothing;
end $$;
